language: php

php:
  - "7.1"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  # - pear install pear/PHP_CodeSniffer
  # - phpenv rehash
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit
  # - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers

